// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7n7oPiOzB4CvJUnJmDNgXuKS_30n4v10',
    appId: '1:1076251224991:web:b66b2041f54bdccced6baa',
    messagingSenderId: '1076251224991',
    projectId: 'practice-89847',
    authDomain: 'practice-89847.firebaseapp.com',
    storageBucket: 'practice-89847.firebasestorage.app',
    measurementId: 'G-QRTL7TCNR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnA0_Ei2k3-hR82sc4_VJeghy8Jwh9bu4',
    appId: '1:1076251224991:android:fc12e2f991d6f26ced6baa',
    messagingSenderId: '1076251224991',
    projectId: 'practice-89847',
    storageBucket: 'practice-89847.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDevEH-X5ulNabIYFx97XmQ_t-pisF2-Kg',
    appId: '1:1076251224991:ios:a6f41da58ba26f39ed6baa',
    messagingSenderId: '1076251224991',
    projectId: 'practice-89847',
    storageBucket: 'practice-89847.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevEH-X5ulNabIYFx97XmQ_t-pisF2-Kg',
    appId: '1:1076251224991:ios:a6f41da58ba26f39ed6baa',
    messagingSenderId: '1076251224991',
    projectId: 'practice-89847',
    storageBucket: 'practice-89847.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7n7oPiOzB4CvJUnJmDNgXuKS_30n4v10',
    appId: '1:1076251224991:web:798c58f49ec8a48aed6baa',
    messagingSenderId: '1076251224991',
    projectId: 'practice-89847',
    authDomain: 'practice-89847.firebaseapp.com',
    storageBucket: 'practice-89847.firebasestorage.app',
    measurementId: 'G-FC2S36GH1J',
  );
}
